### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Erbit** [jp112sdl/JP-HB-Devices-addon#11]
Hi.
I am sorry that I wrote this in the wrong place but I have not found a better one.

Congratulations on the idea and implementation. I really like your project. I will make several devices for myself. They will be very useful.

I have three questions:
- are you planning to build a universal IR remote control?
- are you planning to build a universal 433 Mhz RF remote control?
- are you planning to build an air quality sensor, e.g. based on PMS3003?

The universal IR remote control should remember the sent signal from the original remote control. The more signals it could remember the better ;) Similarly, a universal RF remote control.

These two universal remote controls can control multiple devices at home.

Regarding PMS3003 - the theme of smog recently is popular and it's great to have such information in the home automation ;).

Best regards.
Robert

**Comment by jp112sdl** [comment]
Hi!

> - are you planning to build a universal IR remote control?

No, there are no plans. 
You think about a 868MHz receiver that can send IR signals i.e. to a TV?

> - are you planning to build a universal 433 Mhz RF remote control?

Also - no. I don't have any 433 Mhz devices. They are mostly unidirectional.
The only pluggable 433MHz outlet I had in my installation I've converted to 868MHz.

> - are you planning to build an air quality sensor, e.g. based on PMS3003?

I've tried to use a BME680 to build an IAQ sensor. It's suitable for battery use, but the measurement itself is too complicated (for me).

The PMS3003 is only a dust sensor like the SDS011 ?
Sounds interesting, but there is not really use case for me.

Maybe we can use the homematic forum for discussions like this?
There is a huge community and an extra sub section for hardware development: https://homematic-forum.de/forum/viewforum.php?f=76

**Comment by Erbit** [comment]
> Maybe we can use the homematic forum for discussions like this?
> There is a huge community and an extra sub section for hardware development: https://homematic-forum.de/forum/viewforum.php?f=76

Thank you for link. This will be a very good place for further discussion. I have to read foum first of all, so that I do not repeat issues.


> You think about a 868MHz receiver that can send IR signals i.e. to a TV?
Yes, I will look in the forum;)
 
> The PMS3003 is only a dust sensor like the SDS011 ?
Yes, very similar.


Once again, I congratulate you on the interesting addition to HomeMatic.
Robert.
