### ISSUE TITLE
Installation der Version 2.8 nicht möglich

### ISSUE THREAD

**Issue by pekae** [jp112sdl/JP-HB-Devices-addon#13]
die aktuelle Version lässt sich unter Raspberrymatic (3.45.7.20190622) bei mir nicht installieren.

Entweder " BAD GATEWAY"

oder 

Ein Fehler ist aufgetreten: addon&#x2F; addon&#x2F;uninstall_hb-uni-sen-iaq addon&#x2F;install_hb-ou-mp3-led addon&#x2F;install_hb-uni-rgb-led-ctrl addon&#x2F;firmware&#x2F; addon&#x2F;install_hb-uni-senact-8-8 addon&#x2F;uninstall_hb-dis-ep-xxx addon&#x2F;install_hb-uni-senact-4-4 addon&#x2F;uninstall_hb-ou-mp3-led addon&#x2F;uninstall_hb-uni-rgb-led-ctrl addon&#x2F;install_hb-dis-ep-xxx addon&#x2F;install_hb-uni-sen-wea addon&#x2F;uninstall_hb-uni-senact-4-4 addon&#x2F;install_hb-uni-sen-dummy-beacon addon&#x2F;uninstall_hb-uni-sen-temp addon&#x2F;install_hb-lc-sw2-fm addon&#x2F;uninstall_hb-uni-senact-8-8 addon&#x2F;install_hb-uni-sen-lev-tof addon&#x2F;install_hb-uni-sen-cap-moist-t addon&#x2F;js&#x2F; addon&#x2F;install_hb-lc-sw12-fm addon&#x2F;install_hb-uni-sen-temp-ir addon&#x2F;install_hb-uni-sen-dist-us addon&#x2F;uninstall_hb-uni-sen-wea addon&#x2F;uninstall_hb-uni-sen-cap-moist addon&#x2F;uninstall_hb-uni-s

**Comment by jp112sdl** [comment]
Was meinst du mit "BAD GATEWAY"? Wo an welcher Stelle wird dir das angezeigt?

**Comment by pekae** [comment]
Ich habe mehrere verschiedene Arten versucht
Systemsteuerung : Zusatzsoftware
Oder System-Update

Bei System-Update ohne direkte url - kommt Bad Gateway
Bei direkter Download URL kommen die vielen Fehlermeldungen


Mit freundlichen Gruß

Peter Kästner

**Comment by jp112sdl** [comment]
Ich kanns leider nicht nachvollziehen, was/wie du es machst.

Die Vorgehensweise, um Zusatzsoftware zu installieren, ist allgemein folgende:
1.) Addon herunterladen: https://github.com/jp112sdl/JP-HB-Devices-addon/releases/download/2.8/jp-hb-devices-addon.tgz

2.) In der WebUI Einstellungen->Systemsteuerung->Zusatzsoftware aufrufen.
Dort "Datei auswählen" anklicken und die heruntergeladene Datei _jp-hb-devices-addon.tgz_ anklicken.
Anschließend auf "Installieren" klicken

**Comment by pekae** [comment]
Das hatte ich ja auch versucht- ging auch nicht

Problem ist mittlerweile gelöst, hab erst deinstalliert und dann neue Version installiert 

Das ging ohne Probleme 

Danke für die Mühe 


Mit freundlichen Gruß

Peter Kästner
