### ISSUE TITLE
CCU3 Version

### ISSUE THREAD

**Issue by audi2010** [jp112sdl/JP-HB-Devices-addon#15]
Im Readme steht:
lauffähig unter CCU / RaspberryMatic Firmware 2.31.x - 2.45.7 | 3.37.x - 3.47.10

Ich nutze 3.47.15
Kann ich die beibehalten?

**Comment by jp112sdl** [comment]
Das weiß ich nicht, da ich die 3.47.10 einsetze.

> Kann ich die beibehalten?

..heißt ja, dass du bereits auf einer früheren Firmware das Addon installiert hattest nun auf 3.47.15 aktualisiert hast?
Das weißt du ja am besten, ob noch alles läuft wie soll :)

**Comment by jp112sdl** [comment]
Ich kann Entwarnung geben. 
Die 3.47.15 ist auch kompatibel.

**Comment by audi2010** [comment]
Danke
