### ISSUE TITLE
Mehrer HB-UNI-RGB-LED-CTRL gleichzeitig betreiben

### ISSUE THREAD

**Issue by TheBund** [jp112sdl/JP-HB-Devices-addon#24]
Hi
Es ist nicht möglich mehrer HB-UNI-RGB Controller gleichzeitig an RaspberryMatic anzulernen.
Nur das erste Gerät scheint im Posteingang auf, bzw bei bereits angelerntem Controller gar keines. 

RaspberryMatic 3.51.6.20200420/Pi3
JP-HB-Devices-addon 2.23

Jedes Gerät hat natürlich eine andere Seriennummer....

**Comment by jp112sdl** [comment]
Die Geräte unterscheiden sich auch alle in _Device ID_ **UND** _Seriennummer_ ?

**Comment by TheBund** [comment]
Mit geänderter  Device ID und Device SERIAL funktioniert es!

Danke
