### ISSUE TITLE
Kompatibilität zum hmland Gateway-Emulator.

### ISSUE THREAD

**Issue by Systm21** [jp112sdl/JP-HB-Devices-addon#27]
Hallo Jerome, 
wie ist das eigentlich bei denjenigen, die noch den guten alten HM-CONFIG-USB mit dem hmland Emulator nutzen? Kann man dort auch irgendwie deine Homebrew Sensoren benutzen? Wäre genial!

Grüße

**Comment by jp112sdl** [comment]
Hi,

dieses Addon läuft ausschließlich auf einer CCU (CCU2, CCU3, RaspberryMatic, pivCCU, debmatic).

> die noch den guten alten HM-CONFIG-USB mit dem hmland Emulator nutzen?

Ich kenne weder das eine noch das andere ^^ 😎

**Comment by Systm21** [comment]
Du hast oder hattest den Emulator doch sogar mal auf Github geforked O.o

Also keine Chance das deine Sensoren darüber in Fhem o.ä. Supported werden?

**Comment by jp112sdl** [comment]
> Du hast oder hattest den Emulator doch sogar mal auf Github geforked O.o

Ja, wegen hmsniff mittels HM-MOD-UART. Hab ich nur mal kurz aufm Mac getestet

> Also keine Chance das deine Sensoren darüber in Fhem o.ä. Supported werden?

Da musst du mal im FHEM Forum fragen. Soweit ich weiß, werden ein paar Geräte sogar schon unterstützt.
