### ISSUE TITLE
Probleme mit HB-UNI-RGB-LED-CTRL 

### ISSUE THREAD

**Issue by braindead1** [jp112sdl/JP-HB-Devices-addon#3]
Ich habe das aktuelle Addon 1.26 installiert und einen HB-UNI-RGB-LED-CTRL angelernt. Der Aktor lässt sich problemlos steuern, allerdings gibt es andere Probleme.

In der Geräte Liste wird das Icon nicht angezeigt:
![gerate](https://user-images.githubusercontent.com/2136249/48676572-cfc94380-eb68-11e8-9ae0-bcdccf0b5845.png)

Unter Einstellungen Geräte werden keine Icons angezeigt und auch die Typenbezeichnung fehlet:
![gerate einstellungen](https://user-images.githubusercontent.com/2136249/48676586-fab39780-eb68-11e8-9a10-90958326219e.png)

Das Löschen des Browser Caches und eine Neuinstallation des Addons hat das Problem nicht behoben.

**Comment by braindead1** [comment]
Kommando zurück. Nachdem ich den Cache nochmals gelöscht habe, funktioniert es jetzt problemlos.

**Comment by jp112sdl** [comment]
Hi.
Mal nen anderen Browser probieren.
Oder die CCU neustarten.
Kann nur ein Cache-Problem sein.
