### ISSUE TITLE
Eine Frage zu SD Karte

### ISSUE THREAD

**Issue by akula3** [jp112sdl/JP-HB-Devices-addon#30]
Ist eine SD Karte unbedingt notwendig für den Betrieb des Addons?

**Comment by jp112sdl** [comment]
SD Karte? 
Falls du von einer CCU2 sprichst - nein, die SD Karte ist dort nur für Diagramme notwendig

**Comment by akula3** [comment]
Alles klar, danke für die Rückmeldung! Und ich habe tatsächlich die CCU2 :-)
Mich hat nur der Satz "Bitte etwas Geduld haben - je nach Geschwindigkeit der SD Karte kann die Installation u.U. mehrere Minuten in Anspruch nehmen!" in der Anleitung etwas verwirrt.

**Comment by jp112sdl** [comment]
Ah, verstehe. 
Ja das bezieht sich auf die CCU3 / RaspberryMatic etc, was direkt auf einer SD Karte läuft.
