### ISSUE TITLE
local build device addon not working 

### ISSUE THREAD

**Issue by trilu2000** [jp112sdl/JP-HB-Devices-addon#31]
i cloned your repo, added some files and executed the build script.
I got a jp-hb-devices-addon.tgz file without any error code. 
But when i tried to install it, the ccu says: Error127, Es ist ein unbekannter Fehler aufgetreten.

Looking into the archive it looks ok - comparing it with your files i recognize to miss the subfolder PaxHeader

**Comment by trilu2000** [comment]
can be closed - textfiles in your repo are in a windows file format - dos2unix did the magic

**Comment by jp112sdl** [comment]
> can be closed - textfiles in your repo are in a windows file format - dos2unix did the magic
i am wondering how this can work for you?

Welche Dateien denn genau?
Auf der CCU selbst mischt eQ-3 auch beide Zeilenumbrüche... ich hatte da noch nie Probleme.
Nur halt [beim Patchen](https://homematic-forum.de/forum/viewtopic.php?f=76&t=51927&p=623265#p623191)

**Comment by trilu2000** [comment]
zuerst hatte ich das Problem bei der build.sh, als das beseitigt war, habe ich das tgz archiv erstellen können.
Allerdings eben mit Fehlermeldung beim installieren. Danach hatte ich noch das update_script und jp-hb-devices-addon.

Irgendwann hatte ich dann noch mal neu gecloned und plötzlich ging es auch ohne dos2unix - vielleicht hat mir auch github einen Streich gespielt...
