### ISSUE TITLE
FHEM-Support?

### ISSUE THREAD

**Issue by cablesky** [jp112sdl/JP-HB-Devices-addon#4]
Hallo!

Tolles Teil!
Gibt's das Plugin auch für FHEM? Wäre super!

**Comment by jp112sdl** [comment]
Hi.

Von mir nicht, da ich FHEM nicht kenne.

Im FHEM Forum habe ich mal gelesen, dass es zumindest eine teilweise Integration (einiger Geräte) gibt?
Kann mich aber auch irren.
