### ISSUE TITLE
The link refering to the updates does not open a new window

### ISSUE THREAD

**Issue by grobiballon** [jp112sdl/JP-HB-Devices-addon#43]
If you klick on the link for updates in the overview "Zusatzsoftware" it does not open a new window/tab. Handling would be easier if the CCU browser tab remains and a new will be opened to find the update files.

**Comment by grobiballon** [comment]
Version 5.3
The link on the right side works perfectly, but not the "Herunterladen"/"Download" button.

**Comment by jp112sdl** [comment]
I can't reproduce it.
When I click on "Herunterladen", it opens a new tab

**Comment by grobiballon** [comment]
I just checked it again with Firefox 89.0.1 nad Chrome 91.0.4472.114.
In both Browsers the same "issue".

**Comment by jp112sdl** [comment]
Sorry... I really cannot help you with this.
<img src="http://g.recordit.co/pVJa9ChsdW.gif" />

**Comment by grobiballon** [comment]
What the hell ???
![Animation](https://user-images.githubusercontent.com/36332615/122992646-a4550800-d3a6-11eb-8a11-a69efdd975cf.gif)

**Comment by jp112sdl** [comment]
Can you check the browser console for javascript errors?

Button "Herunterladen" uses `onclick="openUrl...`

And `openUrl` is declared as
```
      openUrl = function(url)
      {
        window.open(url);
      }; 
```
in [/www/config/cp_software.cgi#L446-L449](https://github.com/eq-3/occu/blob/8cb51174c2bc8c4b33df50a96b82c90e8092f79c/WebUI/www/config/cp_software.cgi#L446-L449)

**Comment by jp112sdl** [comment]
https://www.w3schools.com/jsref/met_win_open.asp

"The open() method opens a new browser window, or a new tab, **depending on your browser settings** and the parameter values."

`window.open` has no additional parameters given, so it uses your browser default.

All in all, it has nothing to do with the addon itself.
