### ISSUE TITLE
Unübliche Meldung bei Deinstallation des AddOn's

### ISSUE THREAD

**Issue by Baxxy13** [jp112sdl/JP-HB-Devices-addon#48]
Da ich heute mal dein AddOn (5.6) zu Testzwecken auf verschiedenen Systemen installiert/deinstalliert habe ist mir bei der Deinstallation was aufgefallen.
Normalerweise sollte der Hinweis "Deinstallieren wurde erfolgreich ausgeführt" kommen.
Hier sieht das etwas "anders" aus.
![RM-JP_HB-Device_Deinstallation](https://user-images.githubusercontent.com/54898249/140167739-b6cdbea3-60e7-4f42-ab3e-49fc22e1be7e.JPG)
Nach Klick auf OK passiert erstmal nichts. Schließe und öffne ich das Zusatzsoftware-Fenster ist das AddOn aber weg.

Normalerweise sieht das so aus und nach druck auf OK schließt sich das "Zusatzsoftware-Fenster" (automatisch) kurz und wird neu geöffnet.

![RM-SG_HB-Device_Deinstallation](https://user-images.githubusercontent.com/54898249/140168630-e8429a46-86b2-4691-afec-e60763b744b9.JPG)

Nicht dramatisch, nur etwas verwirrend. ;-)

Systeme: Pi3B/Pi4B/Tinker und HA-OS-AddOn
RM: Nightly 3.61.4.20211103

**Comment by jp112sdl** [comment]
Kann ich nicht reproduzieren
<img src="http://g.recordit.co/c6FqDTiNwK.gif" />

**Comment by Baxxy13** [comment]
Hmm...
![GIF 03 11 2021 19-36-58](https://user-images.githubusercontent.com/54898249/140172168-65bee97c-af92-47e5-94ab-2d6f2b2efc75.gif)

**Comment by jp112sdl** [comment]
Scheint von hier zu kommen:
https://github.com/eq-3/occu/blob/master/WebUI/www/config/cp_software.cgi#L493-L499

Aber warum das (bei dir) passiert... keine Ahnung

**Comment by jp112sdl** [comment]
Ändere doch bitte mal an eben genannter Stelle
```
  if {[catch {exec $script $op}]} {
    puts "Failure"
  }
```

in 
```
  if {[catch {exec $script $op} result]} {
    puts $result
  }
```

Dann sollte der Grund für die `catch`-Exception vor dem "Success" angezeigt werden.

**Comment by Baxxy13** [comment]
Kurzer Zwischenbericht:
Das tritt auch ohne CUxD-AddOn und auch auf einem werksresetteten System auf. 
Die Änderungen mache ich nachher mal rein. Jetzt ist erstmal Couch Zeit.

**Comment by Baxxy13** [comment]
Ich muss doch fummeln... 
Leider kann ich den Fehlertext nicht kopieren, daher nur Screenshots.
![JP_unin1](https://user-images.githubusercontent.com/54898249/140197702-4d95ed88-4895-4c49-b137-61b48ab279be.JPG)
![JP_unin2](https://user-images.githubusercontent.com/54898249/140197718-07309324-263c-4d77-8bda-9d2756c31e00.JPG)
![JP_unin3](https://user-images.githubusercontent.com/54898249/140197726-f5a0bd2e-9e52-423f-8282-76d0aa3b94e1.JPG)

Hilft dir das?

**Comment by jp112sdl** [comment]
Leider nicht, das ist abgeschnitten, da fehlt noch jede Menge Text.
Wäre dann also sinnvoll, den Exception-Text in eine Datei zu schreiben.

Tritt der Fehler auf einem Pi auf? 
Ich hab die Deinstallation bei mir in VirtualBox getestet, da kam der Fehler nicht.
Vielleicht ist es irgendein Zeit-Problem.

**Comment by jp112sdl** [comment]
Bei mir kam die Fehlermeldung jetzt auch, allerdings bei der Deinstallation von CUxD.
Muss dann also eher was OCCU-spezifisches sein.
Ich lass das Ticket hier aber erstmal noch offen, um die Fehlerbehandlung der CCU noch zu verbessern

**Comment by Baxxy13** [comment]
Moin,
die ersten Screenshots waren von der HA-OS AddOn Version auf nem Pi3B+ mit SSD-Boot. 
Die letzten Screenshots (Fehlertext) und das gif waren vom Tinkerboard-S. 
Beide Systeme sollten m.E. mit eMMC / SSD eigentlich flott genug sein.
Wenn du mir zeigst wie ich den Fehlertext in eine Datei umleiten kann, würde ich das mal testen.

**Comment by jp112sdl** [comment]
Kannst du mit dem referenzierten PR was anfangen?

**Comment by jp112sdl** [comment]
Ja ok, das habe ich schon behoben.
Ein anderes Skript räumt die eigenen Bilder schon weg.

Aber das Skript als solches dürfte trotzdem mit Exit Code 0 beendet werden.
Der `rm` Befehl ist nicht der letzte.

**Comment by Baxxy13** [comment]
Bei mir sieht's exakt so aus wie bei Jens.
Daher halte ich mich erstmal raus. 
Stehe aber zum testen bereit.

**Comment by jp112sdl** [comment]
Bei der Version sollten keine rm-Fehler mehr kommen.


[jp-hb-devices-addon.txt](https://github.com/jp112sdl/JP-HB-Devices-addon/files/7476549/jp-hb-devices-addon.txt)
_.txt in .tgz umbenennen_

**Comment by jens-maus** [comment]
> Aber das Skript als solches dürfte trotzdem mit Exit Code 0 beendet werden. Der `rm` Befehl ist nicht der letzte.

Das kann nicht sein, denn der tclsh exec befehl sollte nur dann in das if() laufen wenn das auszuführende Programm/Skript einen exit code != 0 hat.

**Comment by Baxxy13** [comment]
> Bei der Version sollten keine rm-Fehler mehr kommen.

Installation / DeInstallation ohne Auffälligkeiten.
Tinker-S mit Nightly 3.61.4.20211104

**Comment by jp112sdl** [comment]
> Das kann nicht sein, denn der tclsh exec befehl sollte nur dann in das if() laufen wenn das auszuführende Programm/Skript einen exit code != 0 hat.

Hmm ja, aber am rm kann es nicht liegen.
Kommt nach dem fehlerhaften Befehl noch ein "funktionierender" ist der exit Code 0.

<img width="458" alt="Bildschirmfoto 2021-11-04 um 17 50 21" src="https://user-images.githubusercontent.com/18190139/140383152-80c2208b-e547-4515-9b3e-8ddc69e4752f.png">

Das letzte Kommando in meinem "uninstall" ist das Löschen von sich selbst:
https://github.com/jp112sdl/JP-HB-Devices-addon/blob/7c4850e49d24f06e065c11ca9b969c0881053792/src/rc.d/jp-hb-devices-addon#L306-L307

Das Versucht die WebUI zwar auch, aber erst **nach** dem Ausführen des Shell-Skripts:
```
  if { "$op" == "uninstall" } {
    exec rm -rf $script
  }
```
und das führt nicht mehr zu einem Fehler im Sinne der WebUI-Anzeige.


> Installation / DeInstallation ohne Auffälligkeiten.

Na das klingt schon mal gut

**Comment by jens-maus** [comment]
> Hmm ja, aber am rm kann es nicht liegen.
> Kommt nach dem fehlerhaften Befehl noch ein "funktionierender" ist der exit Code 0.

Du hast nicht zufällig ein `set -e` oder so im shell skript damit alle Fehler während des ablaufen summiert in einem exit code 1 dann landen?

**Comment by jp112sdl** [comment]
Nein, hab ich nicht.

**Comment by jp112sdl** [comment]
Wenn es mit der neuen Addon Version jetzt geht, dann nehm ich das mal so als glücklichen Umstand hin.

Über den PR https://github.com/jens-maus/RaspberryMatic/pull/1500 sollte aber trotzdem nachgedacht werden.
