### ISSUE TITLE
Fehler bei AddOn Installation 5.7

### ISSUE THREAD

**Issue by Hypnos3** [jp112sdl/JP-HB-Devices-addon#50]
ich habe sei t dem update ein rotes Dreieck und es gibt folgendes Log:
[jp-hb-devices-addon-error (2).log](https://github.com/jp112sdl/JP-HB-Devices-addon/files/7530858/jp-hb-devices-addon-error.2.log)

Meine Firmware ist RaspberryMatic: 3.59.6.20211009

Ich frage mich ob hier was bei mir kaputt ist.
Danke

**Comment by jp112sdl** [comment]
Hi,

ja da konnten einige Patche nicht korrekt angewendet werden.

Ich würde dich bitten, die RaspberryMatic Firmware 3.59.6.20211009 einfach noch mal drüber zu installieren.

**Comment by Hypnos3** [comment]
Da seit heute RaspberryMatic 3.61.5.20211113 verfügbar ist, hab ich diese installiert und die Meldung ist weg.

Danke
