### ISSUE TITLE
Fehler beim Update / Warndreieck: Was tun ?

### ISSUE THREAD

**Issue by guny74** [jp112sdl/JP-HB-Devices-addon#58]
Hallo, 

ich habe von einer Version 3.3 - versucht mit Methode 1 auf 5.8 upzudaten. Es gab kein Reboot zwischen deinstallation und installation. Jetzt bekomme ich aber dennoch das rote Dreieck.
Ich kann auch die Logs herunterladen wie auf Ihrer Seite beschrieben. Aber was kann ich danach tun ?

**Comment by jp112sdl** [comment]
"Variante 2" der Readme auf der Startseite ausführen.

**Comment by jp112sdl** [comment]
Gibt es hier Neuigkeiten oder kann das Ticket zu ?

**Comment by guny74** [comment]
Hallo,

sorry, ja habe es wieder auf diese weise gerade ziehen können. 

Danke für die Hilfe.

**Comment by jp112sdl** [comment]
Prima!
