### ISSUE TITLE
Was muss ich machen um eigene HB Geräte zu installieren

### ISSUE THREAD

**Issue by Xento** [jp112sdl/JP-HB-Devices-addon#59]
Wie schon im Titel geschrieben, was muss ich machen um eigene Homebrew Geräte anzulegen.
Es gibt ja den Ordner customized_firmware, wenn ich dort meine XML rein packen, sollte sie ja auch Updates des Addons überleben.

Allerdings stelle ich mir noch folgende Fragen:
1. wie löse ich eine Installation des Gerätes aus
2. wo packe ich die Bilder zum Gerät hin, damit sie auch eine Aktualisierung des Addons überleben
3. was muss ich machen um eine neue Version der XML-Datei installieren zu lassen
4. was passiert, wenn ich eine XML entfernen wird das Gerät dann überall deinstalliert und wie starte ich das

**Comment by jp112sdl** [comment]
Rein mit einer XML und Bildchen ist es nicht getan.

Um ein eigenes Gerät mit der ID `neues_geraet` anzulegen, damit die CCU es "erkennt", ist im einfachsten Fall (keine eigenen Bezeichnungen für Werte/Parameter):
- das `DEV_PATHS` Array in der _/www/webui/webui.js_ zu erweitern
```JS
+DEV_PATHS['<neues_geraet>'] = new Object();
+DEV_PATHS['<neues_geraet>']['50'] = '/config/img/devices/50/<neues_geraet>_thumb.png';
+DEV_PATHS['<neues_geraet>']['250'] = '/config/img/devices/250/<neues_geraet>.png';
+DEV_HIGHLIGHT['<neues_geraet>'] = new Object();
+DEV_LIST.push('<neues_geraet>');
```

- das `DEV_PATHS` Array in der  _/www/config/devdescr/DEVDB.tcl_ zu erweitern
```
array set DEV_PATHS       {<neues_geraet> {{50 /config/img/devices/50/<neues_geraet>_thumb.png} {250 /config/img/devices/250/<neues_geraet>.png}}...
```

Die Bilder sind entsprechend abzulegen in 
- _/www/config/img/devices/50_ in 50x50 Pixel Größe als Thumbnail (`<neues_geraet>_thumb.png`)
- _/www/config/img/devices/250_ in 250x250 Pixel Größe (`<neues_geraet>.png`)


Und dazu kommt nun noch die XML ins Spiel, mit gleich lautender ID
```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
...
  <supported_types>
    <type name="Ein neues Geraet" id="<neues_geraet>" priority="2">
...
    </type>
```

Vielleicht hilft dir das hier noch etwas weiter: https://homematic-forum.de/forum/viewtopic.php?f=76&t=66649

Das Thema ist mega komplex und die Frage "wie mache ich da ein neues Gerät rein" nicht leicht/allgemeingültig zu beantworten.

**Comment by Xento** [comment]
Ich hab mich mal getraut das Addon von Version 2.8 auf die aktuelle zu aktualisieren.
Daher hab ich mich gefragt, wie man am besten eigene Geräte ablegen kann ohne Angst haben zu müssen, dass alles überschrieben wird wenn man das Addon aktualisiert.

Ich hatte einen Aktor selber erstellt, der meine Markise mit Licht (hat nur ne Fernbedienung mit Auf/Zu/Stopp/Licht) bedienen kann.
Mittlwerweile wird er nur noch als Unknown in der CCU angezeigt, funktioniert aber noch, da ich ja nur die standard Parameter vom Rollo-Aktor und von nem Schalter genommen habe.
Glaub das liegt an den fehlenden Patches der Webui.js ...

Währe cool, wenn man auch das Installscript und die Icons zusammen ablegen könnte damit das alles automatisch wieder eingerichtet werden kann.
Ich könnte jetzt mein altes Installerscript im Addonverzeichnis ablegen, aber beim Update währe das wieder weg.
Wofür gibts denn dann den customized_firmwares Ordner, wenn die dort abgelegten Firmwares nicht komplett widerhergestellt werden können.
Man könnte es ja so einbauen, dass man in diesem Ordner für seine eigenen Firmwares einen Unterordner erstellt, in dem man dann die XML, alle Bilder und andere Patche ablegen kann und dann beim Update das dortige Installscript ausgeführt wird.

Wie wird denn aktuell die webui.js gepatched?
Früher war das ja im Installscript der Firmware drin.

**Comment by jp112sdl** [comment]
@Xento Ticket kann zu ?
