### ISSUE TITLE
HB-Uni-Sen-WEA &  Openhab3

### ISSUE THREAD

**Issue by quantenquark** [jp112sdl/JP-HB-Devices-addon#61]
Hi Jerome,

I am working with the latest version of the Rasperrymatic OS / HB add-on. After successfully integrating the HB-Uni-Sen-WEA I am wondering why some of the available parameters are not available in Openhab 3.0. 
These are Lux, UV, and Lightning Detection. 
Checking the Openhab logs there are no warning or error message present at all.

Would you happen to know the reason? I am not sure if this is related to the Openhab binding.
Your support is really appreciated ;-)

Best Achim

**Comment by jp112sdl** [comment]
Hi!

Sorry, but I'm not using openHab so I can't help with that.
Maybe it only supports eQ3 native ("known") datapoint types or so.... don't know.

In ioBroker everything is ok.

**Comment by quantenquark** [comment]
Hi Jerome, thanks for your statement. I will try with ioBroker as the value conversion by OpenHAB is also questionable. 

73
Achim
