### ISSUE TITLE
Fehlermeldung nach Rapsberrymatic Update auf 3.65.6.20220723

### ISSUE THREAD

**Issue by diddi68** [jp112sdl/JP-HB-Devices-addon#64]
Hallo Jérôme,

ich hab heute ein Update auf die 3.65.6.20220723 durchgeführt und leider erst danach den Hinweis bekommen, die "JP HB Devices" vorher auf 6.0 upzudaten (war 5.9a). Trotz des Updates auf 6.0 bekomm ich das Warnmeldungssymbol mit den Fehlern
`### REVOKE patch file /usr/local/addons/jp-hb-devices-addon/patch/common/datapointconfigurator.fn.patch
Hunk 1 FAILED 148/148.
     var CN_WIN_SC_SENSOR   = "WIN_SC_SENSOR.";
     var CN_WINDOW          = "WINDOW.";
 
+    var CN_RFID_BUTTON     = "RFIDBTN.";
+    var CN_IRRC_BUTTON     = "IRRCBTN.";
+    var CN_IBTN_BUTTON     = "IBTN.";
+    var CN_SERVO           = "SERVO.";
+    var CN_AIRFLAP         = "AIRFLAP.";
+    var CN_JPWINDOW        = "JPWND.";
+    var CN_GDS             = "GDS.";
+    var CN_FAN             = "FAN.";
+    var CN_PFS             = "PFS.";
+    var CN_LDRSC           = "LDRSC.";
+    var CN_CRGSC           = "CRGSC.";
+    var CN_PWRSC           = "PWRSC.";
+    var CN_CONDSC          = "CONDSC.";
+    
     var CN_EVENT_INTERFACE = "EVENT_INTERFACE.";
     var CN_NOT_ACTIVE = "CHANNEL_NOT_ACTIVE";
 
- done`

und

`### REVOKE patch file /usr/local/addons/jp-hb-devices-addon/patch/common/rhs.fn.patch
Hunk 1 FAILED 1/1.
 function ::CreateWndRotSensor() {
+  object objVoltage = cObj.DPByHssDP("OPERATING_VOLTAGE");
+
   WriteLine("<td>");
     WriteLine("<table class='ControlBtnOff CLASS02514' id='"#chnId#"OpenH' >");
     WriteLine("<tr>");
- done`

Wie krieg ich das wieder hin? Genügt bei mir auch - wie bei fraeggle - ein erneutes Installieren der 3.65.6.20220723?

**Comment by jp112sdl** [comment]
Hi,

einfach noch mal die RaspberryMatic Version drüber installieren.

**Comment by diddi68** [comment]
Okay. Vielen Dank für deinen Hinweis.
