### ISSUE TITLE
Update killte die CCU WebUI

### ISSUE THREAD

**Issue by Fiiti** [jp112sdl/JP-HB-Devices-addon#65]
Ähnlich wie in dem anderen Issue vor einer Stunde https://github.com/jp112sdl/JP-HB-Devices-addon/issues/64 
habe ich hier auch das Problem gehabt, das nach Update CCU auf letzte Version ein Ausrufezeichen zeigte. Dann Update JB Addon auf 6.0 - Ausrufezeichen bleibt. Genauen Fehler kann ich nicht mehr sagen, da.... =>

==> Ich habe danach das Add-On deinstalliert. => Nun kommt keine CCU3 WebUI mehr hoch.

- XML-API calls laufen. (z. B. http://192.168.1.123:8181/x.exe?Antwort=dom.GetObject(%22CUxD.CUX0202111:1.TOGGLE%22).State(1))
- Cuxd Maintanace läuft auch via URl  https://192.168.1.123/addons/cuxd/maintenance.html
- Mehrfach Reboots bringen nichts.
- Beim Aufruf der CCU Webseite via https://192.168.1.123/ kommt nur "not Found". Nicht mal ein 403 oder 500 oder sonst was.
Auch via http ist es identisch.

Was kann ich nun machen?

**Comment by jp112sdl** [comment]
Das hat nichts mit dem Addon zu tun.

Grundsätzlich würde ich hier raten: SD Karte raus, RM Image neu draufschreiben, von blanker RM booten und Backup einspielen.
