### ISSUE TITLE
Addon jp-hp-devices-addon

### ISSUE THREAD

**Issue by MartinKrause57** [jp112sdl/JP-HB-Devices-addon#66]
Hallo
Ich wollte das adddon 6 installieren. Habe aber übersehen , das dies vor dem update auf 3.65.6 pivccu geshehen ist. Wie kann ich ein update durchführen.
Martin

**Comment by jp112sdl** [comment]
Was genau ist passiert?
Du hast erst 3.65.6 und dann erst das Addon?

**Comment by MartinKrause57** [comment]
Genau. Dadurch gibt es Fehler nach dem Update .
Ich wollte dann pivccu3 downgraden. Leider habe ich keine Anleitung gefunden. Ich habe eine Sicherung. Kann man nach dem downgrade das addon installieren und anschließend pivccu wieder upgraden. ? Oder gibt es eine andere Vorgehensweise.
Martin

**Comment by jp112sdl** [comment]
Du brauchst nur die aktuelle 3.65.6 noch mal drüberinstallieren (#64 , #62 , #58 , #50)

**Comment by MartinKrause57** [comment]
Hat geklappt.
Danke
