### ISSUE TITLE
Frage zur Version

### ISSUE THREAD

**Issue by fraeggle** [jp112sdl/JP-HB-Devices-addon#69]
Hi hab nur eine Frage, weil es steht bei der Version 6:
.....lauffähig unter CCU / RaspberryMatic Firmware 3.47.10 - 3.65.6 [inkl. x86]

Nun ist die Raspberrymatic schon bei 3.65.11.20221005.
Gibt es etwas zu beachten?

Gruß Peter

**Comment by jp112sdl** [comment]
Hi, das kann ich dir nicht sagen, da ich mich noch nicht weiter mit einer neueren CCU/RM-Version beschäftigt habe.

**Comment by fraeggle** [comment]
OK  ich mein es sieht zumindest so aus als wenn meine Wetterstation und der RFID Leser noch gehen... ;-)

**Comment by fraeggle** [comment]
dann würde ich dies hier erst mal schließen....... war ja auch nur ne Frage  ;-)

Danke an die beteiligten für die Software.........

Gruß Peter
