### ISSUE TITLE
Update auf Raspberrymatic 3.71.12

### ISSUE THREAD

**Issue by GameWatchProjects** [jp112sdl/JP-HB-Devices-addon#73]
Hallo, ist ein Update des Device Addon's auf Raspberrymatic Rev. 3.71.12 vorgesehen?

**Comment by jp112sdl** [comment]
Hi. Sollte eigentlich mit der aktuellen Version so funktionieren.
Hab die README nur (noch) nicht angepasst.

**Comment by stan23** [comment]
Ich hab mit RaspberryMatic 3.71.12 noch keine Probleme gefunden.

**Comment by jp112sdl** [comment]
Prima. Dann ändere ich das mal in der README
