### ISSUE TITLE
HM_LC_Sw1PBU_FM alt FW als HM-LC-SwX erkannt

### ISSUE THREAD

**Issue by der2of6** [jp112sdl/JP-HB-Devices-addon#76]
Hallo,
ich habe seit fast 10 Jahren 2 HM_LC_Sw1PBU_FM mit der alternativen Firmware https://github.com/jabdoa2/Asksin_HM_LC_Sw1PBU_FM und FHEM im Einsatz.
Aktuell steht der Wechsel der HM Komponenten auf RaspberryMatic an. 

Nach meinem Verständnis sollte diese FW mit diesem Add-ON auch auf der CCU laufen. 

Wenn ich versuche das Gerät mit der CUU (Mit Add-On) zu installieren, dann wird der Schalter als HM-LC-SwX erkannt mit über 60 Kanälen. Kurz darauf ist dann auch der Duty Cycle bei 100%.

Nun die Frage: Braucht die FW noch eine bestimmte Einstellung, damit sie mit der CCU und dem Add-ON richtig funtioniert oder kann der Fehler woanders liegen?

**Comment by stan23** [comment]
Das Gerät meldet sich mit der ID 0xF0A9:
https://github.com/jabdoa2/Asksin_HM_LC_Sw1PBU_FM/blob/master/Register.h#L15

Diese ID kennt die Zentrale nicht und Jérômes Add-On auch nicht.

Du solltest stattdessen diesen Sketch benutzen:
https://github.com/jp112sdl/Beispiel_AskSinPP/tree/master/examples/HB-LC-Sw1PBU-FM

**Comment by der2of6** [comment]
Danke, da war der Knoten im Hirn
