### ISSUE TITLE
Konfigurationsdaten stehen zur Übertragung an

### ISSUE THREAD

**Issue by yveszemp** [jp112sdl/JP-HB-Devices-addon#9]
Hallo als erstes ein echter Lob für diese Arbeit und dass wir dies benutzen dürfen. Ich habe mir nun ein Modell nachgebaut, den SenAct 4-4. Jedoch wenn ich da Programme erstelle, erscheint unter den Servicemeldungen die Nachricht, dass Konfigurationsdaten zur übertragung anstehen, diese werde aber nie übertragen, und es funktioniert nur der erste Aktor, die anderen kann ich über ein Programm nicht ansteuern, nur wenn ich diese manuell im Geräte Bedienen Menu verwende. Was mache ich falsch ? 
![Homematic](https://user-images.githubusercontent.com/49389039/55705055-2501d680-59de-11e9-9d34-1c3d6f225501.png)

Liegt es an der Device ID ? Ich habe da bei der ID das letzte bit als 0X02 gesetzt, sowie die ID auf JPSENACT02, ansonsten hätte ich einen zweiten auch nicht korrekt anlernen können.

Vielen Dank für ein Feedback.

**Comment by jp112sdl** [comment]
Hi,

da das nichts mit dem Addon zu tun hat, könntest du bitte diese Anfrage noch mal beim HB-UNI-SenAct-4-4 Projekt erstellen?
https://github.com/jp112sdl/HB-UNI-SenAct-4-4/

Danke!

**Comment by yveszemp** [comment]
Sorry ja klar, hat ja nichts mit dem Addon zu tun, habe es im Aktor selber eingefügt. Danke
